name: "bim_bim_app"
description: "BIM BIM application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  swipe_cards: ^2.0.0+1
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  flutter_secure_storage: ^9.2.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png" 
  min_sdk_android: 21