spring:
  application:
    name: bim-bim
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master-changelog.yaml

rest:
  client:
    matching:
      base-url: ${MATCHING_SERVICE_BASE_URL}

jwt:
  secretKey: ${JWT_SECRET_KEY}
  expirationTime: 3600000 # 1 hour in milliseconds

springdoc:
  swagger-ui:
    path: /api-docs

minio:
  bucket: images
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  url: ${MINIO_URL}

